name: Lint and Analyze Code

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Set up PowerShell
      uses: actions/setup-powershell@v2

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Determine file types
      id: determine_files
      run: |
        echo "PYTHON_FILES=$(git ls-files '*.py')" >> $GITHUB_ENV
        echo "POWERSHELL_FILES=$(git ls-files '*.ps1')" >> $GITHUB_ENV
        echo "BASH_FILES=$(git ls-files '*.sh')" >> $GITHUB_ENV

    - name: Lint Python code
      if: env.PYTHON_FILES != ''
      run: |
        pylint ${{ env.PYTHON_FILES }} > python_lint_report.txt

    - name: Lint PowerShell code
      if: env.POWERSHELL_FILES != ''
      run: |
        pwsh -Command "Invoke-ScriptAnalyzer -Path ${{ env.POWERSHELL_FILES }} | Out-File -FilePath powershell_lint_report.txt"

    - name: Lint Bash code
      if: env.BASH_FILES != ''
      run: |
        shellcheck ${{ env.BASH_FILES }} > bash_lint_report.txt

    - name: Combine reports
      run: |
        cat python_lint_report.txt powershell_lint_report.txt bash_lint_report.txt > combined_lint_report.txt

    - name: Upload report
      uses: actions/upload-artifact@v2
      with:
        name: lint-report
        path: combined_lint_report.txt
