name: Lint and Analyze Code

on: [push, pull_request]

permissions:
  contents: write

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Unzip folders
      run: |
        for zip in *.zip; do
          unzip -o "$zip" -d "${zip%.*}"
        done

    - name: Determine folders
      id: determine_folders
      run: |
        echo "FOLDERS=$(ls -d */)" >> $GITHUB_ENV

    - name: Lint code in each folder
      run: |
        for folder in ${{ env.FOLDERS }}; do
          echo "Processing folder: $folder"
          python_files=$(find $folder -name '*.py')
          powershell_files=$(find $folder -name '*.ps1')
          bash_files=$(find $folder -name '*.sh')

          if [ -n "$python_files" ]; then
            pylint $python_files > ${folder%/}/python_lint_report.txt
          fi

          if [ -n "$powershell_files" ]; then
            pwsh -Command "Invoke-ScriptAnalyzer -Path $powershell_files | Out-File -FilePath ${folder%/}/powershell_lint_report.txt"
          fi

          if [ -n "$bash_files" ]; then
            shellcheck $bash_files > ${folder%/}/bash_lint_report.txt
          fi
        done

    - name: Commit reports to repository
      run: |
        git config --global user.name 'github-actions[bot]'
        git config --global user.email 'github-actions[bot]@users.noreply.github.com'
        for folder in ${{ env.FOLDERS }}; do
          if [ -f ${folder%/}/python_lint_report.txt ] || [ -f ${folder%/}/powershell_lint_report.txt ] || [ -f ${folder%/}/bash_lint_report.txt ]; then
            git add ${folder%/}/*_lint_report.txt
          fi
        done
        git commit -m 'Add individual lint reports for each folder'
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
