name: Lint and Analyze Code

on:
  push:
    paths:
      - '**'  # Trigger on any file addition
    branches:
      - '**'  # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Determine file types
      id: determine_files
      run: |
        echo "PYTHON_FILES<<EOF" >> $GITHUB_ENV
        git ls-files '*.py' | sed 's/^/"/;s/$/"/' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "POWERSHELL_FILES<<EOF" >> $GITHUB_ENV
        git ls-files '*.ps1' | sed 's/^/"/;s/$/"/' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        echo "BASH_FILES<<EOF" >> $GITHUB_ENV
        git ls-files '*.sh' | sed 's/^/"/;s/$/"/' >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Lint Python code
      if: env.PYTHON_FILES != ''
      run: |
        echo "" > python_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && pylint "$file" >> python_lint_report.txt || true
        done <<< "${{ env.PYTHON_FILES }}"

    - name: Lint PowerShell code
      if: env.POWERSHELL_FILES != ''
      run: |
        echo "" > powershell_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && pwsh -Command "Invoke-ScriptAnalyzer -Path $file" >> powershell_lint_report.txt || true
        done <<< "${{ env.POWERSHELL_FILES }}"

    - name: Lint Bash code
      if: env.BASH_FILES != ''
      run: |
        echo "" > bash_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && shellcheck "$file" >> bash_lint_report.txt || true
        done <<< "${{ env.BASH_FILES }}"

    - name: Combine reports
      run: |
        echo "" > combined_lint_report.txt
        [ -s python_lint_report.txt ] && cat python_lint_report.txt >> combined_lint_report.txt
        [ -s powershell_lint_report.txt ] && cat powershell_lint_report.txt >> combined_lint_report.txt
        [ -s bash_lint_report.txt ] && cat bash_lint_report.txt >> combined_lint_report.txt

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: combined_lint_report.txt
