name: Lint and Analyze Code

on:
  push:
    paths:
      - '**'  # Trigger on any file addition
    branches:
      - '**'  # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Determine file types
      id: determine_files
      run: |
        PYTHON_FILES=$(git ls-files '*.py')
        POWERSHELL_FILES=$(git ls-files '*.ps1')
        BASH_FILES=$(git ls-files '*.sh')

        echo "PYTHON_FILES=$PYTHON_FILES" >> $GITHUB_ENV
        echo "POWERSHELL_FILES=$POWERSHELL_FILES" >> $GITHUB_ENV
        echo "BASH_FILES=$BASH_FILES" >> $GITHUB_ENV

    - name: Lint Python code
      if: env.PYTHON_FILES != ''
      run: |
        > python_lint_report.txt
        for file in ${{ env.PYTHON_FILES }}; do
          [ -n "$file" ] && pylint "$file" >> python_lint_report.txt || true
        done

    - name: Lint PowerShell code
      if: env.POWERSHELL_FILES != ''
      run: |
        > powershell_lint_report.txt
        for file in ${{ env.POWERSHELL_FILES }}; do
          [ -n "$file" ] && pwsh -Command "Invoke-ScriptAnalyzer -Path '$file'" >> powershell_lint_report.txt || true
        done

    - name: Lint Bash code
      if: env.BASH_FILES != ''
      run: |
        > bash_lint_report.txt
        for file in ${{ env.BASH_FILES }}; do
          [ -n "$file" ] && shellcheck "$file" >> bash_lint_report.txt || true
        done

    - name: Combine reports
      run: |
        > combined_lint_report.txt
        [ -s python_lint_report.txt ] && cat python_lint_report.txt >> combined_lint_report.txt
        [ -s powershell_lint_report.txt ] && cat powershell_lint_report.txt >> combined_lint_report.txt
        [ -s bash_lint_report.txt ] && cat bash_lint_report.txt >> combined_lint_report.txt

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: combined_lint_report.txt
