name: Lint and Analyze Code

on:
  push:
    paths:
      - '**'  # Trigger on any file addition
    branches:
      - '**'  # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Determine file types
      id: determine_files
      run: |
        echo "PYTHON_FILES=$(git ls-files '*.py' | tr '\n' ' ')" >> $GITHUB_ENV
        echo "POWERSHELL_FILES=$(git ls-files '*.ps1' | tr '\n' ' ')" >> $GITHUB_ENV
        echo "BASH_FILES=$(git ls-files '*.sh' | tr '\n' ' ')" >> $GITHUB_ENV

    - name: Lint Python code
      if: env.PYTHON_FILES != ''
      run: |
        pylint ${{ env.PYTHON_FILES }} > python_lint_report.txt || true

    - name: Lint PowerShell code
      if: env.POWERSHELL_FILES != ''
      run: |
        pwsh -Command "Invoke-ScriptAnalyzer -Path '${{ env.POWERSHELL_FILES }}' | Out-File -FilePath powershell_lint_report.txt"

    - name: Lint Bash code
      if: env.BASH_FILES != ''
      run: |
        shellcheck ${{ env.BASH_FILES }} > bash_lint_report.txt || true

    - name: Combine reports
      run: |
        touch combined_lint_report.txt
        [ -f python_lint_report.txt ] && cat python_lint_report.txt >> combined_lint_report.txt
        [ -f powershell_lint_report.txt ] && cat powershell_lint_report.txt >> combined_lint_report.txt
        [ -f bash_lint_report.txt ] && cat bash_lint_report.txt >> combined_lint_report.txt

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: combined_lint_report.txt
