name: Lint and Analyze Code

on:
  push:
    paths:
      - '**'  # Trigger on any file addition
    branches:
      - '**'  # Run on all branches

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install Python linters
      run: |
        pip install pylint

    - name: Install PowerShell
      run: |
        sudo apt-get update
        sudo apt-get install -y powershell

    - name: Install ShellCheck
      run: |
        sudo apt-get install -y shellcheck

    - name: Determine file types
      id: determine_files
      run: |
        # Determine Python files
        echo "PYTHON_FILES<<EOF" >> $GITHUB_ENV
        python_files=$(git ls-files '*.py')
        echo "$python_files" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        # Determine PowerShell files
        echo "POWERSHELL_FILES<<EOF" >> $GITHUB_ENV
        powershell_files=$(git ls-files '*.ps1')
        echo "$powershell_files" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
        
        # Determine Bash files
        echo "BASH_FILES<<EOF" >> $GITHUB_ENV
        bash_files=$(git ls-files '*.sh')
        echo "$bash_files" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

        # Output the lists to the logs
        echo "Python files: $python_files"
        echo "PowerShell files: $powershell_files"
        echo "Bash files: $bash_files"

    - name: Lint Python code
      if: ${{ env.PYTHON_FILES != '' }}
      run: |
        > python_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && pylint "$file" >> python_lint_report.txt || true
        done <<< "${{ env.PYTHON_FILES }}"

    - name: Lint PowerShell code
      if: ${{ env.POWERSHELL_FILES != '' }}
      run: |
        > powershell_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && pwsh -Command "Invoke-ScriptAnalyzer -Path '$file'" >> powershell_lint_report.txt || true
        done <<< "${{ env.POWERSHELL_FILES }}"

    - name: Lint Bash code
      if: ${{ env.BASH_FILES != '' }}
      run: |
        > bash_lint_report.txt
        while IFS= read -r file; do
          [ -n "$file" ] && shellcheck "$file" >> bash_lint_report.txt || true
        done <<< "${{ env.BASH_FILES }}"

    - name: Check report files before combining
      run: |
        ls -l python_lint_report.txt powershell_lint_report.txt bash_lint_report.txt

    - name: Combine reports
      run: |
        > combined_lint_report.txt
        [ -s python_lint_report.txt ] && cat python_lint_report.txt >> combined_lint_report.txt || echo "No Python linting issues found" >> combined_lint_report.txt
        [ -s powershell_lint_report.txt ] && cat powershell_lint_report.txt >> combined_lint_report.txt || echo "No PowerShell linting issues found" >> combined_lint_report.txt
        [ -s bash_lint_report.txt ] && cat bash_lint_report.txt >> combined_lint_report.txt || echo "No Bash linting issues found" >> combined_lint_report.txt

    - name: Upload report
      uses: actions/upload-artifact@v4
      with:
        name: lint-report
        path: combined_lint_report.txt
